# Generated by Django 6.0 on 2025-12-31 13:35

import db_file_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=db_file_storage.storage.DatabaseFileStorage(), upload_to=''),
        ),
    ]
